---
title: "Assignment 1"
author: "Ted Ladas -s2124289"
date: "10/20/2020"
output:
  pdf_document: default
  html_document: default
---

# Libraries

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
require(MASS)
```

## Exercise 1

## Exercise 2

## Exercise 3

# Setup of full dataframe

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
set.seed(1903)
rows = 500
z1 = rnorm(rows)
z2 = rnorm(rows)
z3 = rnorm(rows)

y1 = 1 + z1
y2 = 5 + 2*z1 + z2
df = data.frame("Y1"=y1, "Y2"=y2)
```

# -- 3.a

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
df_1 = df
a=2;b=0
y2_rule = a*(y1-1) + b*(y2-5) + z3 < 0

y2_obs = y2[y2_rule]
y2_miss = y2[!y2_rule]

for(i in 1:rows){
  if(y2_rule[i]){
    df_1$Y2[i] = NA
  }
}

plot(density(y2_obs), col="darkblue", xlab="Y2", main="MNAR")
lines(density(y2_miss), col = "red")
lines(density(df$Y2), col = "darkgreen")
legend(7.5,0.22,legend = c("Y2 observed", "Y2 missing", "Y2 full"), 
       col = c("darkblue", "red", "darkgreen"),
       lty=c(1,1,1),
       bty="n")
```

# -- 3.b

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
fit = lm(df_1$Y2 ~ Y1, data = df_1)
# checking for correlation between Y2 and residuals
plot(fit$fitted.values, residuals(fit), xlab = "Fitted values", ylab = "Residuals")
# checking for irregularities in the distribution of residuals
qqnorm(rstandard(fit), xlim = c(-3, 3), ylim = c(-3, 3))
qqline(rstandard(fit), col = 2)
summary(fit)
```

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
df_2 = df_1
predicted_slm = predict(fit, newdata = df_1) + rnorm(nrow(df_1), 0, sigma(fit))
df_2$Y2 = ifelse(is.na(df_2$Y2), predicted_slm, df_2$Y2)

plot(density(df_2$Y2), col="darkblue", xlab="Y2", main="Stochastic Linear Regression")
lines(density(df$Y2), col = "red")
legend(8,0.15,legend = c("slm Y2", "full Y2"), 
       col = c("darkblue", "red"),
       lty=c(1,1),
       bty="n")
```

#-- 3.c

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
df_3 = df
a=0;b=2
y2_rule = a*(y1-1) + b*(y2-5) + z3 < 0

y2_obs = y2[y2_rule]
y2_miss = y2[!y2_rule]

for(i in 1:rows){
  if(y2_rule[i]){
    df_1$Y2[i] = NA
  }
}

plot(density(y2_obs), col="darkblue", xlab="Y2", main="MNAR", xlim=c(-5,15))
lines(density(y2_miss), col = "red")
lines(density(df$Y2), col = "darkgreen")
legend(9,0.25,legend = c("Y2 observed", "Y2 missing", "Y2 full"), 
       col = c("darkblue", "red", "darkgreen"),
       lty=c(1,1,1),
       bty="n")
```

#-- 3.d

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
fit = lm(df_1$Y2 ~ df_3$Y1, data = df_1)
# checking for correlation between Y2 and residuals
plot(fit$fitted.values, residuals(fit), xlab = "Fitted values", ylab = "Residuals")
# checking for irregularities in the distribution of residuals
qqnorm(rstandard(fit), xlim = c(-3, 3), ylim = c(-3, 3))
qqline(rstandard(fit), col = 2)
summary(fit)
```

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
df_4 = df_1
predicted_slm = predict(fit, newdata = df_1) + rnorm(nrow(df_1), 0, sigma(fit))
df_4$Y2 = ifelse(is.na(df_4$Y2), predicted_slm, df_4$Y2)

plot(density(df_4$Y2), col="darkblue", xlab="Y2", main="Stochastic Linear Regression")
lines(density(df$Y2), col = "red")
legend(8,0.15,legend = c("slm Y2", "full Y2"), 
       col = c("darkblue", "red"),
       lty=c(1,1),
       bty="n")
```
## Exercise 4

#-- 4.a

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
load(file = "data/databp.RData")
print("Complete Case")

mean_fc = mean(databp$recovtime, na.rm=TRUE)
sd_fc = sd(databp$recovtime, na.rm=TRUE)
corr_recovtime_logdose_fc = cor(databp$recovtime, databp$logdose, use = "complete")
corr_recovtime_boodp_fc = cor(databp$recovtime, databp$bloodp, use = "complete")

print(paste0("mean: ", mean_fc))
print(paste0("standard dev: " , sd_fc))
print(paste0("recovtime & dose: " , corr_recovtime_logdose_fc))
print(paste0("recovtime & bloodp: " , corr_recovtime_boodp_fc))
```
#-- 4.b

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
recovtime_mi = ifelse(is.na(databp$recovtime), mean_fc, databp$recovtime)

mean_mi = mean(recovtime_mi, na.rm=TRUE)
sd_mi = sd(recovtime_mi, na.rm=TRUE)
corr_recovtime_logdose_mi = cor(recovtime_mi, databp$logdose)
corr_recovtime_boodp_mi = cor(recovtime_mi, databp$bloodp)

print(paste0("mean: ", mean_mi))
print(paste0("standard dev: " , sd_mi))
print(paste0("recovtime & dose: " , corr_recovtime_logdose_mi))
print(paste0("recovtime & bloodp: " , corr_recovtime_boodp_mi))
```
#-- 4.c

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
fit = lm(databp$recovtime ~ databp$logdose + databp$bloodp, data = databp)

# checking for correlation between Y2 and residuals
plot(fit$fitted.values, residuals(fit), xlab = "Fitted values", ylab = "Residuals")
# checking for irregularities in the distribution of residuals
qqnorm(rstandard(fit), xlim = c(-3, 3), ylim = c(-3, 3))
qqline(rstandard(fit), col = 2)

# summary(fit)
# Rsqr seems very bad, need to explore more
predicted_ri = predict(fit, newdata=databp)
recovtime_ri = ifelse(is.na(databp$recovtime), predicted_ri, databp$recovtime)

mean_ri = mean(recovtime_ri, na.rm=TRUE)
sd_ri = sd(recovtime_ri, na.rm=TRUE)
corr_recovtime_logdose_ri = cor(recovtime_ri, databp$logdose)
corr_recovtime_boodp_ri = cor(recovtime_ri, databp$bloodp)

print(paste0("mean: ", mean_ri))
print(paste0("standard dev: " , sd_ri))
print(paste0("recovtime & dose: " , corr_recovtime_logdose_ri))
print(paste0("recovtime & bloodp: " , corr_recovtime_boodp_ri))
```
```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}

predicted_sri <- predict(fit, newdata = databp) + rnorm(nrow(databp), 0, sigma(fit))
recovtime_sri = ifelse(is.na(databp$recovtime), predicted_sri, databp$recovtime)

mean_sri = mean(recovtime_sri, na.rm=TRUE)
sd_sri = sd(recovtime_sri, na.rm=TRUE)
corr_recovtime_logdose_sri = cor(recovtime_sri, databp$logdose)
corr_recovtime_boodp_sri = cor(recovtime_sri, databp$bloodp)

print(paste0("mean: ", mean_sri))
print(paste0("standard dev: " , sd_sri))
print(paste0("recovtime & dose: " , corr_recovtime_logdose_sri))
print(paste0("recovtime & bloodp: " , corr_recovtime_boodp_sri))

# very skewed results, need to investigate
```
#--4.e

```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
predicted_hd = predict(fit, newdata=databp)
ind_hd = which(is.na(databp$recovtime) == FALSE)


# recovtime_hd = ifelse(is.na(databp$recovtime), donated_hd, databp$recovtime)
```


```{r, include=TRUE, message=FALSE, tidy=TRUE, fig.align='center'}
# predihdi <- predict(fitri, newdata = databp)
# 
# indhdi <- which(is.na(databp$recovtime) == FALSE)
# # MSD <- matrix(, ncol = 3)
# # for (i in length(predihdi[-indhdi])) {
#   df_MSD[,1] <- as.data.frame((predihdi[indhdi]-predihdi[-indhdi][1])**2)
#   df_MSD[,2] <- as.data.frame((predihdi[indhdi]-predihdi[-indhdi][2])**2)
#   df_MSD[,3] <- as.data.frame((predihdi[indhdi]-predihdi[-indhdi][3])**2)
#   MSD[,1] <- which.min(df_MSD[,1])
#   MSD[,2] <- which.min(df_MSD[,2])
#   MSD[,3] <- which.min(df_MSD[,3])
# # }
# 
# donor1 <- sample(MSD[1], 1, replace = TRUE) #WRONG
# donor2 <- sample(MSD[2], 1, replace = TRUE) #WRONG
# donor3 <- sample(MSD[3], 1, replace = TRUE) #WRONG
# 
# rthd <- c(databp$recovtime[is.na(databp$recovtime) == FALSE],
#         databp$recovtime[MSD[1]], databp$recovtime[MSD[2]],
#         databp$recovtime[MSD[3]])
# 
# mhd <- mean(rthd)
# sehd <- sd(rthd)/sqrt(N)
# 
# mhd; sehd
```



